apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack-beta.yml
    kompose.version: 1.16.0 (HEAD)
  labels:
    fint.stack: utdanning-timeplan
    fint.role: consumer
  name: consumer-utdanning-timeplan
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      fint.stack: utdanning-timeplan
      fint.role: consumer
  template:
    metadata:
      labels:
        fint.stack: utdanning-timeplan
        fint.role: consumer
    spec:
      restartPolicy: Always
      containers:
        - name: consumer-utdanning-timeplan
          image: fintlabs.azurecr.io/consumer-utdanning-timeplan:0.4.8-3.1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /utdanning/timeplan/health
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              cpu: "100m"
              memory: "1Gi"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: fint.audit.mongo.databasename
              value: fint-audit-beta
            - name: fint.audit.mongo.connection-string
              valueFrom:
                secretKeyRef:
                  name: fint-audit
                  key: mongodb
            - name: fint.cache.manager
              value: default
            - name: fint.events.orgIds
              value: health.fintlabs.no
            - name: fint.hazelcast.kubernetes.enabled
              value: "true"
            - name: fint.hazelcast.kubernetes.namespace
              value: default
            - name: fint.hazelcast.kubernetes.labelName
              value: fint.stack
            - name: fint.hazelcast.kubernetes.labelValue
              value: utdanning-timeplan
            - name: fint.relations.default-base-url
              value: https://beta.felleskomponent.no
            - name: server.context-path
              value: /utdanning/timeplan
