version: '3'

services:
  provider:
    image: dtr.rogfk.no/fint-beta/provider:PR-9
    ports:
      - "8252:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/timeplan/provider
      fint.events.orgIds: "rogfk.no,vsware.ie,sam.obrien,ssetest1.no,ssetest2.no,afk.no,t-fk.no"
      fint.events.component: beta
      fint.events.env: beta
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-beta
      fint.provider.sse-timeout-minutes: 19
      fint.hazelcast.members: consumer,provider
      endpoints.trace.sensitive: "false"
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  consumer:
    image: dtr.rogfk.no/fint-beta/consumer-utdanning-timeplan:0.1.0-3.0.0
    ports:
      - "8253:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/timeplan
      fint.events.orgIds: "rogfk.no,vsware.ie,sam.obrien,ssetest1.no,ssetest2.no,afk.no,t-fk.no"
      fint.events.component: beta
      fint.events.env: beta
      fint.relations.default-base-url: "https://beta.felleskomponent.no"
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-beta
      fint.hazelcast.members: consumer,provider
      fint.cache.manager: hazelcast
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  health-adapter:
    image: dtr.rogfk.no/fint-beta/health-adapter:1.1.0
    environment:
      TZ: Europe/Oslo
      springfox.title: "Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: http://provider:8080/utdanning/timeplan/provider/sse/%s
      fint.adapter.status-endpoint: http://provider:8080/utdanning/timeplan/provider/status
      fint.adapter.response-endpoint: http://provider:8080/utdanning/timeplan/provider/response
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
