version: '3.3'
secrets:
  fint-audit-mongo:
    external: true
services:
  provider:
    image: dtr.fintlabs.no/beta/provider:RC-4
    secrets:
    - source: fint-audit-mongo
      target: fint.audit.mongo.connection-string
    ports:
    - 8252:8080
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/timeplan/provider
      fint.events.orgIds: health.fintlabs.no
      fint.audit.mongo.databasename: fint-audit-beta
      fint.hazelcast.members: consumer,provider
      fint.provider.assets.endpoint: https://admin-beta.fintlabs.no/api/components/assets/utdanning_timeplan
    logging:
      driver: journald
      options:
        tag: utdanning-timeplan/provider
    deploy:
      placement:
        constraints:
        - node.role == worker
        - node.labels.com.docker.ucp.collection == shared
      replicas: 1
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 3
        window: 120s
  consumer:
    image: dtr.fintlabs.no/beta/consumer-utdanning-timeplan:0.4.5-3.1.0
    secrets:
    - source: fint-audit-mongo
      target: fint.audit.mongo.connection-string
    ports:
    - 8253:8080
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/timeplan
      fint.events.orgIds: health.fintlabs.no
      fint.relations.default-base-url: https://beta.felleskomponent.no
      fint.audit.mongo.databasename: fint-audit-beta
      fint.hazelcast.members: consumer,provider
      fint.cache.manager: hazelcast
    logging:
      driver: journald
      options:
        tag: utdanning-timeplan/consumer
    deploy:
      placement:
        constraints:
        - node.role == worker
        - node.labels.com.docker.ucp.collection == shared
      replicas: 1
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 3
        window: 120s
  health-adapter:
    image: dtr.fintlabs.no/beta/health-adapter:1.2.1
    environment:
      TZ: Europe/Oslo
      springfox.title: Health Adapter
      fint.adapter.organizations: health.fintlabs.no
      fint.adapter.sse-endpoint: https://beta.felleskomponent.no/utdanning/timeplan/provider/sse/%s
      fint.adapter.status-endpoint: https://beta.felleskomponent.no/utdanning/timeplan/provider/status
      fint.adapter.response-endpoint: https://beta.felleskomponent.no/utdanning/timeplan/provider/response
      fint.oauth.enabled: 'true'
      fint.oauth.username: health@fintlabs.no
      fint.oauth.password: '}!=sCArQf2tTsgdQ,8XQXxe.KHnChyu?;%N3<wwXbow"*rKv2Ya)yt*gH]w4v%DJ'
      fint.oauth.access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
      fint.oauth.client-id: 659a3a1c-f4df-48d9-8ca1-c01c08eaaee4
      fint.oauth.client-secret: NScfTIgx76Be-qc_tz5uc80Lpnz37oErbdXYEbslIhNDuWyz-W5sCj6NTo4NFJjcbrD6VH0w6Q_SWAUuh8xkkg
      fint.oauth.scope: fint-client
    logging:
      driver: journald
      options:
        tag: utdanning-timeplan/health-adapter
    deploy:
      placement:
        constraints:
        - node.role == worker
        - node.labels.com.docker.ucp.collection == shared
      replicas: 1
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
    - provider
